language: python
python:
    - "2.7"

# Cache PlatformIO packages using Travis CI container-based infrastructure
sudo: false
cache:
    directories:
        - "~/.platformio"

env:

    - PLATFORMIO_CI_SRC=examples/ESPmanager-example/ESPmanager-example.ino

install:
    - pip install -U platformio
    - platformio lib install 293  
    - git clone https://github.com/sticilface/ESPAsyncWebServer /tmp/ESPAsyncWebServer
    - cd /tmp/ESPAsyncWebServer
    - git checkout FileFallbackHandler
    - mkdir /tmp/build

script:
    
    - platformio ci --build-dir="/tmp/build" --keep-build-dir --lib="." --lib="/tmp/ESPAsyncWebServer" --board=nodemcu
   
